AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'spec/*'
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Max: 15
Style/OptionalBooleanParameter:
  Enabled: false
Metrics/AbcSize:
  Max: 20